
-- Enable UUID extension if needed in future, though currently using Integer IDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. BOOKS & CATALOG
-- ==========================================
CREATE TABLE backend_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(13) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    ddc_code VARCHAR(20) NOT NULL,
    call_number VARCHAR(50),
    barcode_id VARCHAR(50) UNIQUE,
    shelf_location VARCHAR(50),
    cover_url VARCHAR(500),
    
    -- Status Tracking
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    hold_expires_at TIMESTAMPTZ,
    
    -- Metadata
    marc_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    material_type VARCHAR(50) NOT NULL DEFAULT 'REGULAR',

    -- Inventory Stats
    queue_length INTEGER NOT NULL DEFAULT 0,
    last_inventoried DATE,

    -- Data Constraints
    CONSTRAINT check_status CHECK (status IN ('AVAILABLE', 'LOANED', 'LOST', 'PROCESSING', 'HELD'))
);

-- Indexes for Kiosk High-Speed Search
CREATE INDEX idx_book_isbn ON backend_book(isbn);
CREATE INDEX idx_book_ddc ON backend_book(ddc_code);
CREATE INDEX idx_book_call_number ON backend_book(call_number);
CREATE INDEX idx_book_barcode ON backend_book(barcode_id);
-- GIN Index for searching within MARC21 JSON blobs
CREATE INDEX idx_book_marc ON backend_book USING GIN (marc_metadata);


-- ==========================================
-- 2. PATRONS (USERS)
-- ==========================================
CREATE TABLE backend_patron (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    patron_group VARCHAR(20) NOT NULL,
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    fines DECIMAL(6, 2) NOT NULL DEFAULT 0.00,

    CONSTRAINT check_patron_group CHECK (patron_group IN ('STUDENT', 'TEACHER', 'LIBRARIAN', 'ADMINISTRATOR'))
);

CREATE INDEX idx_patron_student_id ON backend_patron(student_id);


-- ==========================================
-- 3. CIRCULATION RULES (THE MATRIX)
-- ==========================================
CREATE TABLE backend_circulationrule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patron_group VARCHAR(20) NOT NULL,
    material_type VARCHAR(20) NOT NULL,
    loan_days INTEGER NOT NULL DEFAULT 14,
    max_items INTEGER NOT NULL DEFAULT 3,
    fine_per_day DECIMAL(4, 2) NOT NULL DEFAULT 0.50
);


-- ==========================================
-- 4. ACTIVE LOANS
-- ==========================================
CREATE TABLE backend_loan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES backend_book(id) ON DELETE CASCADE,
    patron_id BIGINT NOT NULL REFERENCES backend_patron(id) ON DELETE CASCADE,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    due_date TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ
);

CREATE INDEX idx_loan_patron ON backend_loan(patron_id);
CREATE INDEX idx_loan_book ON backend_loan(book_id);
CREATE INDEX idx_loan_returned ON backend_loan(returned_at) WHERE returned_at IS NULL;


-- ==========================================
-- 5. HOLDS & RESERVATIONS
-- ==========================================
CREATE TABLE backend_hold (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES backend_book(id) ON DELETE CASCADE,
    patron_id BIGINT NOT NULL REFERENCES backend_patron(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMPTZ
);

CREATE INDEX idx_hold_queue ON backend_hold(book_id, created_at);


-- ==========================================
-- 6. LIBRARY CALENDAR EVENTS
-- ==========================================
CREATE TABLE backend_libraryevent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    date DATE NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    description TEXT,

    CONSTRAINT check_event_type CHECK (event_type IN ('HOLIDAY', 'EXAM', 'WORKSHOP', 'CLUB', 'GENERAL'))
);

CREATE INDEX idx_event_date ON backend_libraryevent(date);
